### PR TITLE
Implement cytoscape.js

### PR DESCRIPTION
**Pull request by n-peugnet**
So here is the very first working cytoscape graph:

image

You can set your branch's upstream to mine to push commits directly to my branch. (Gihub should give you instructions on how to do it with the CLI)

### CODE REVIEW

**Comment by vincent-peugnet** [comment]
Owwh <3

**Comment by vincent-peugnet** [comment]
Actually, `cose layout` are not very satisfying.

I'm wondering if we should try [cose-bilkent](https://github.com/cytoscape/cytoscape.js-cose-bilkent), that seems to be more powerfull.

**Comment by n-peugnet** [comment]
Of course you can try. It's really easy to setup:

> Download the library:
>
> via npm: `npm install cytoscape-cose-bilkent`
> 
> ES import:
> 
> ```js
> import cytoscape from 'cytoscape';
> import coseBilkent from 'cytoscape-cose-bilkent';
> 
> cytoscape.use( coseBilkent );
> ```

**Comment by n-peugnet** [comment]
In my opinion this is already good to merge

**Pull request merged**
