### PR TITLE
feat: add unsaved changes' asterix indicator

### LINKED ISSUE #17: change alert pop up after AJAX update to "last update" timestamp
Instead of having to press enter key after each update, why not update a "last updated" timestamp in the editor top bar.
That way you can be certified of the update by seing the timestamp changing.

Is it complicated to do that @n-peugnet  ??

- [x] remove alert
- [ ] add lastupdate timestamp

### PR DESCRIPTION
**Pull request by n-peugnet**
Added only asterix. You can easily edit the `changed()` and `saved()` functions to try the emoticon change.

Part of #17

### CODE REVIEW

**Comment by vincent-peugnet** [comment]
Interesting.

At first I thought about the asterix after the title written in the menu bar.

At this place : 

asterixx

`cat`  would become `cat*` when edited

But it is pretty cool in the title as well !

I see just one problem : before, it was the `page title` displayed here and not the `page id`. I think we need to pass this new variable to the js part or something...

**Comment by n-peugnet** [comment]
> `cat` would become `cat*` when edited
> 
> But it is pretty cool in the title as well !

It is important to put the asterix first in the case of the page title. Otherwise it would often be hidden by the size of the tab.

> I see just one problem : before, it was the `page title` displayed here and not the `page id`. I think we need to pass this new variable to the js part or something...

Ah oups. My mistake. I can fix this easily indeed. I'll do it while fixing the conflicts

**Comment by n-peugnet** [comment]
Rebased and fixed the title bug

**Comment by n-peugnet** [comment]
Rebased and fixed the title bug

**Comment by vincent-peugnet** [comment]
> > `cat` would become `cat*` when edited
> > But it is pretty cool in the title as well !
> 
> It is important to put the asterix first in the case of the page title. Otherwise it would often be hidden by the size of the tab.

Yeah right, but as the image I've uploaded is showing you, I was talking about the `page id` present in the `body` not the one in the `head`.

**Comment by n-peugnet** [comment]
vouala

asterix-save

**Comment by n-peugnet** [comment]
update-title
 added a small bonus in 19803db

**Comment by vincent-peugnet** [comment]
https://www.youtube.com/watch?v=2Nat0rOEMCA

**Pull request merged**
