### PR TITLE
Include CodeMirror in edit page

### LINKED ISSUE #11: Implement Code Mirror
https://codemirror.net/

add the ability to use code mirror instead of textarea to have rich text editor for markdown, html, css and js.

Maybe @n-peugnet  can help with that.

### PR DESCRIPTION
**Pull request by n-peugnet**
Hey I started to implement this feature

Left to do:
- [x] update README with npm prerequisite info and build instructions
- [x] add CodeMirror views for the other text areas
- [x] move js sources files to `/src/`
- [x] make font-size work

Closes #11

### CODE REVIEW

**Comment by n-peugnet** [comment]
Now that the js source files are being bundled I think that they should be moved outside of the public assets directory.

Where do you think we should move them @vincent-peugnet ? I guess somewhere in 
the `app` dir ? Maybe `app/js/` ?

**Comment by vincent-peugnet** [comment]
Maybe not in `app/` but even more in parent folder for this kind of materials only used to be bundled once.

For me it's even clearer if there is an `/src/` at root that I will easily exclude from releases.

> PS : the coffee you gave me this morning was sooooo strong !!! (or maybe I was so exited to merge branchs)

**Comment by n-peugnet** [comment]
Ok good point. Also src is the standard for js sources.

**Comment by n-peugnet** [comment]
Okay. There is still a problem: the font-size setting doesn't work with CodeMirror yet

**Comment by vincent-peugnet** [comment]
> Okay. There is still a problem: the font-size setting doesn't work with CodeMirror yet

I knew this would be a problem as CodeMirror seems to be "on top of everything".

This is what I've founded in the manual :

> Customized Styling
> Up to a certain extent, CodeMirror's look can be changed by modifying style sheet files. The style sheets supplied by modes simply provide the colors for that mode, and can be adapted in a very straightforward way. To style the editor itself, it is possible to alter or override the styles defined in codemirror.css.
> 
> Some care must be taken there, since a lot of the rules in this file are necessary to have CodeMirror function properly. Adjusting colors should be safe, of course, and with some care a lot of other things can be changed as well. The CSS classes defined in this file serve the following roles:
> 
> CodeMirror
> The outer element of the editor. This should be used for the editor width, height, borders and positioning. Can also be used to set styles that should hold for everything inside the editor (such as font and font size), or to set a background. Setting this class' height style to auto will make the editor resize to fit its content (it is recommended to also set the viewportMargin option to Infinity when doing this.

**Comment by vincent-peugnet** [comment]
I also appreciate "Install from sources" addition in the `README.md` file !!!

**Comment by vincent-peugnet** [comment]
Oh, I see a quick thing that can be fixed : auto line break should be used for markdown areas as it's set in MichelFortin's script

In the future it should be an option synchronized with the render's options.

**Comment by n-peugnet** [comment]
>Oh, I see a quick thing that can be fixed : auto line break should be used for markdown areas as it's set in MichelFortin's script

I'm not sure what you are talking about. but it's now fully functional and I think you should do the options tweaking yourself to choose exactly what you want.

**Comment by vincent-peugnet** [comment]
> > Oh, I see a quick thing that can be fixed : auto line break should be used for markdown areas as it's set in MichelFortin's script
> 
> I'm not sure what you are talking about. but it's now fully functional and I think you should do the options tweaking yourself to choose exactly what you want.

Okay, I've figured out how to do this : 

    lineWrapping: true

**Pull request merged**
