### PR TITLE
Add release makefile

### LINKED ISSUE #16: Create script or makefile to build the distribution zip
It will be useful to bundle the application later without forgetting steps.

I could make a PR for this once #13 is merged

### PR DESCRIPTION
**Pull request by n-peugnet**
With this Makefile you can run `make dist` which will build a clean zip file for the release.

Closes #16

### CODE REVIEW

**Comment by vincent-peugnet** [comment]
Okay, looks wonderful. I test it now

**Comment by vincent-peugnet** [comment]
where does makefile read the version number for the zip file name ?

In my test, he wrote 1.7.0 but the composer.json, where the version number is stored was 1.7.5

Could it be possible to use this version number as filename source ??

**Comment by n-peugnet** [comment]
Later we could use a release tool like [release-it](https://github.com/release-it/release-it) or [please](https://github.com/adhocore/please) to create the release on GitHub programmatically

**Comment by vincent-peugnet** [comment]
Okay, but as anybody can can generate a release anytime, it would be more precise to use this number ?

It's more independent from git in a way but I think it's fun.

**Comment by n-peugnet** [comment]
In fact the git version number is more precise as it adds le commit number of the current commit when there is no exact tag for it.

Also composer uses the git tags as its version number. So the version field in the composer.json should be removed at some point. To get the version number from the application a VERSION file could be generated by the release tool at each release.

**Comment by vincent-peugnet** [comment]
Okay,

because right now for example, someone create a release not just after a release tag, it create a zip file with a version number that will not be the same as the one written in the software, it's a bit strange.

So maybe what I should do  is to stop increment version number after each commit and wait after any release to do so.

That way it will be well synchronized.

Or you think I should do differently ?

**Comment by n-peugnet** [comment]
Yes this is the principle of a release. The version number should only be incremented when you release a version.

**Comment by vincent-peugnet** [comment]
Okydoc carpacio !

**Pull request merged**
